import type { Metadata } from "next";
import SideNav from "@/components/sideNav";
import MainNav from "@/components/mainNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
      <SideNav
        items={[
          {
            href: "/home",
            icon: "home",
            title: "Home",
          },
          {
            href: "/library",
            icon: "library",
            title: "Library",
          },
          {
            href: "/templates",
            icon: "template",
            title: "Templates",
            badge: 6,
          },
        ]}
        key={0}
      />
      <div className="flex flex-col">
        <MainNav
          items={[
            {
              href: "/home",
              icon: "home",
              title: "Home",
            },
            {
              href: "/library",
              icon: "library",
              title: "Library",
            },
            {
              href: "/templates",
              icon: "template",
              title: "Templates",
              badge: 6,
            },
          ]}
          key={1}
        />
        <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
          {children}
          {/* <div className="flex items-center">
            <h1 className="text-lg font-semibold md:text-2xl">Inventory</h1>
          </div>
          <div
            className="flex flex-1 items-center justify-center rounded-lg border border-dashed shadow-sm"
            x-chunk="dashboard-02-chunk-1"
          >
            <div className="flex flex-col items-center gap-1 text-center">
              <h3 className="text-2xl font-bold tracking-tight">
                You have no products
              </h3>
              <p className="text-sm text-muted-foreground">
                You can start selling as soon as you add a product.
              </p>
              <Button className="mt-4">Add Product</Button>
            </div>
          </div> */}
        </main>
      </div>
    </div>
  );
}
